"""

Revision ID: c5acdbdd4c79
Revises: c6b19d4d1848
Create Date: 2025-12-10 03:13:50.946192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5acdbdd4c79'
down_revision: Union[str, Sequence[str], None] = 'c6b19d4d1848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfiles', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('UserProfiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('UserProfiles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfiles', 'name')
    op.drop_column('UserProfiles', 'email')
    op.drop_column('UserProfiles', 'google_access_token')
    # ### end Alembic commands ###
