"""

Revision ID: fd3ccea49fb7
Revises: c5acdbdd4c79
Create Date: 2025-12-10 03:42:21.649565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3ccea49fb7'
down_revision: Union[str, Sequence[str], None] = 'c5acdbdd4c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserProfiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserProfiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
